### ISSUE TITLE
Found stange pin holes

### ISSUE THREAD

**Issue by micklen** [GadgetReboot/Rotary_Optical_USB#2]
HI,
I found two through holes and wonder what shall be solder in here?
![IMG_2476](https://user-images.githubusercontent.com/23320633/236879294-56b47b0b-39b7-4a84-ab03-72eb0c12c733.jpg)
![IMG_2477 2](https://user-images.githubusercontent.com/23320633/236879307-5a991aeb-fd0f-4928-9d79-aa0caa625bf4.jpg)

**Comment by micklen** [comment]
Second picture is take from below

**Comment by GadgetReboot** [comment]
That's weird, and not in the original design or on my physical boards!   
Here's what the design file looks like on top and bottom in that area.
Did you order directly from PCBWay shared projects or did you upload gerber files manually?

It looks like someone stuck an extra component on the board and manufactured that instead of the original file.  
And it looks like those through holes are shorting those tracks to the ground plane on the bottom side so it may not be able to be ignored.  
To get it up and running I'd take a knife and cut along the 3 green marked areas to make sure it's not connected to ground or a nearby pad.   
Then I'd look over the board to see if there's any other weird stuff thrown in there, and contact the board shop to ask WTF...and get a refund!  I've never had that happen.

![_bottom](https://user-images.githubusercontent.com/34284866/236888087-ffeebb6d-8879-45e9-b272-153376c7fe21.png)
![_top](https://user-images.githubusercontent.com/34284866/236888088-6ae4b626-2f9a-4c5d-a535-c01a6853134f.png)
![_mod](https://user-images.githubusercontent.com/34284866/236890203-8ce25400-e3a5-4fb8-91e9-c7f1da452dbf.png)
